CREATE TABLE USERS (
	ID BIGSERIAL PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	PASSWORD VARCHAR(255) NOT NULL
);

CREATE TABLE POSTS (
	ID BIGSERIAL PRIMARY KEY,
	TITLE TEXT NOT NULL UNIQUE,
	BODY TEXT NOT NULL,
	USER_ID BIGINT NOT NULL,
	CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT (NOW()),
	FOREIGN KEY (USER_ID) REFERENCES USERS (ID)
);
